[package]
name = "proto-termd"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
portable-pty.workspace = true
proto-ipc = { path = "../proto-ipc" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true

