[package]
name = "forge-bench"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
forge-project = { path = "../forge-project" }
forge-search = { path = "../forge-search" }
proto-ipc = { path = "../proto-ipc" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true

[lints]
workspace = true
